services:
  - type: web
    name: mbnt-system
    runtime: node
    nodeVersion: 18.x
    plan: standard
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: mbnt_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - type: postgres
    name: mbnt_db
    ipAllowList: []
    plan: free
